// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzkzboprobefassrckad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6a3pib3Byb2JlZmFzc3Jja2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NTIwOTAsImV4cCI6MjA4NjEyODA5MH0.XZ7gIyESmOa8adtJVhudgMjQtoDR3OvLGeGdK4CJ0tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});